main: kitpvp.Main
version: 0.0.1
name: KitPvP
author: TeamRaiderz

commands:
  kit:
    description: main command
  prefix: 
    description: Change the color of your name
  nick: 
    description: Change the color of your name
  lang: 
    description: Change your language
  kieli: 
    description: Change your language
  test: 
    description: Secret